[webserver]
port = ":8080"

[cache]
max_zoom="16"
type="file"             # cache type
basepath="/cache"       # cache specific config

# register data providers
[[providers]]
name = "world"            # provider name is referenced from map layers
type = "postgis"        # the type of data provider. currently only supports postgis
host = "postgis"        # postgis database host
port = 5432             # postgis database port
database = "world"      # postgis database name
user = "postgres"       # postgis database user
password = ""           # postgis database password
srid = 3857             # The default srid for this provider. If not provided it will be WebMercator (3857)

    [[providers.layers]]
    name = "water"
    sql= """
    select gid, ST_AsBinary(geometry) as geom from public.water_polygons_z2 WHERE 1 >= !ZOOM! AND (geometry && !BBOX!) 
    union all
    select gid, ST_AsBinary(geometry) as geom from public.water_polygons_z3 WHERE 1 < !ZOOM! AND 2 >= !ZOOM! AND (geometry && !BBOX!) 
    union all
    select gid, ST_AsBinary(geometry) as geom from public.water_polygons_z4 WHERE 2 < !ZOOM! AND 3 >= !ZOOM! AND (geometry && !BBOX!) 
    union all
    select gid, ST_AsBinary(geometry) as geom from public.water_polygons_z5 WHERE 3 < !ZOOM! AND 4 >= !ZOOM! AND (geometry && !BBOX!) 
    union all
    select gid, ST_AsBinary(geometry) as geom from public.water_polygons_z6 WHERE 4 < !ZOOM! AND 5 >= !ZOOM! AND (geometry && !BBOX!) 
    union all
    select gid, ST_AsBinary(geometry) as geom from public.water_polygons_z7 WHERE 5 < !ZOOM! AND 6 >= !ZOOM! AND (geometry && !BBOX!) 
    union all
    select gid, ST_AsBinary(geometry) as geom from public.water_polygons_z8 WHERE 6 < !ZOOM! AND 7 >= !ZOOM! AND (geometry && !BBOX!) 
    union all
    select gid, ST_AsBinary(geometry) as geom from public.simplified_water_polygons WHERE 7 < !ZOOM! AND 8 >= !ZOOM! AND (geometry && !BBOX!) 
    union all
    select gid, ST_AsBinary(geometry) as geom from public.water_polygons WHERE 8 < !ZOOM! AND (geometry && !BBOX!) 
    """

[[maps]]
name = "global"
    [[maps.layers]]
    provider_layer = "world.water"
    dont_simplify = true    
  

[[providers]]
name = "osm"            # provider name is referenced from map layers
type = "postgis"        # the type of data provider. currently only supports postgis
host = "postgis"        # postgis database host
port = 5432             # postgis database port
database = "slice"      # postgis database name
user = "postgres"       # postgis database user
password = ""           # postgis database password
srid = 3857             # The default srid for this provider. If not provided it will be WebMercator (3857)

    [[providers.layers]]
    name = "shiproute"
    tablename = "import.osm_shiproute"
    geometry_fieldname = "geometry"
    id_fieldname = "id"

    [[providers.layers]]
    name = "cycleroute"
    tablename = "import.osm_cycleroute"
    geometry_fieldname = "geometry"
    id_fieldname = "id"
    fields = "ref, name"

    [[providers.layers]]
    name = "buildings"
    tablename = "import.osm_buildings"
    geometry_fieldname = "geometry"
    id_fieldname = "id"

    [[providers.layers]]
    name = "admin"
    tablename = "import.osm_admin"
    geometry_fieldname = "geometry"
    id_fieldname = "id"
    fields = "ref, level"

    [[providers.layers]]
    # FIXME: remove unused columns
    name = "landuse"
    sql= """
    select osm_id as gid, ST_AsBinary(geometry) as geom, class, subclass, surface, area from import.osm_landuse_gen8 WHERE 8 >= !ZOOM! AND (geometry && !BBOX!) 
    union all
    select osm_id as gid, ST_AsBinary(geometry) as geom, class, subclass, surface, area from import.osm_landuse_gen9 WHERE 8 < !ZOOM! AND 9 >= !ZOOM! AND (geometry && !BBOX!) 
    union all
    select osm_id as gid, ST_AsBinary(geometry) as geom, class, subclass, surface, area from import.osm_landuse_gen10 WHERE 9 < !ZOOM! AND 10 >= !ZOOM! AND (geometry && !BBOX!) 
    union all
    select osm_id as gid, ST_AsBinary(geometry) as geom, class, subclass, surface, area from import.osm_landuse_gen11 WHERE 10 < !ZOOM! AND 11 >= !ZOOM! AND (geometry && !BBOX!) 
    union all
    select osm_id as gid, ST_AsBinary(geometry) as geom, class, subclass, surface, area from import.osm_landuse_gen12 WHERE 11 < !ZOOM! AND 12 >= !ZOOM! AND (geometry && !BBOX!) 
    union all
    select osm_id as gid, ST_AsBinary(geometry) as geom, class, subclass, surface, area from import.osm_landuse_gen13 WHERE 12 < !ZOOM! AND 13 >= !ZOOM! AND (geometry && !BBOX!) 
    union all
    select osm_id as gid, ST_AsBinary(geometry) as geom, class, subclass, surface, area from import.osm_landuse_gen14 WHERE 13 < !ZOOM! AND 14 >= !ZOOM! AND (geometry && !BBOX!) 
    union all
    select osm_id as gid, ST_AsBinary(geometry) as geom, class, subclass, surface, area from import.osm_landuse WHERE 14 < !ZOOM! AND (geometry && !BBOX!) 
    """

[[maps]]
name = "local"

    [[maps.layers]]
    provider_layer = "osm.landuse"
    min_zoom = 7

    [[maps.layers]]
    provider_layer = "osm.cycleroute"
    min_zoom = 11

    [[maps.layers]]
    provider_layer = "osm.buildings"
    min_zoom = 13

    [[maps.layers]]
    provider_layer = "osm.admin"
    min_zoom = 6

