version: "3.7"
services:
  postgis:
    image: "img-postgis:0.9.1"
    container_name: ${POSTGIS_HOSTNAME}
    networks: 
      - gis
    volumes:
      - ./serve/postgis.conf:/etc/postgresql/postgresql.conf:ro
      - ${HOST_DATABASE_LOCATION}:/pgdata
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - PGDATA=/pgdata
    command: -c 'config_file=/etc/postgresql/postgresql.conf'

  tegola:
    image: "tegola:master"
    container_name: ${TEGOLA_HOSTNAME}
    user: 1000:1000
    depends_on:
      - postgis
    networks: 
      - gis
    volumes:
      - ./serve/config/cyclemap.toml:/data/config.toml:ro
      - ./serve/.cache:/cache
    ports:
      - "127.0.0.1:${TEGOLA_PORT}:8080"
    environment:
      # - TEGOLA_SQL_DEBUG=LAYER_SQL:EXECUTE_SQL
      # - TEGOLA_SQL_DEBUG=LAYER_SQL
      - TEGOLA_SQL_DEBUG=
    command: serve --config /data/config.toml

  preprocessing:
    image: "img-postgis:0.9.1"
    depends_on:
      - postgis
    networks: 
      - gis
    environment:
      - POSTGIS_HOSTNAME=${POSTGIS_HOSTNAME}
      - POSTGIS_USER=${POSTGIS_USER}
      - DATABASE_NAME=${DATABASE_NAME}
    volumes:
      - ./import/preprocessing.sh:/import/preprocessing.sh:ro
    command: bash /import/preprocessing.sh

  borders:
    image: "img-postgis:0.9.1"
    depends_on:
      - postgis
    networks: 
      - gis
    environment:
      - POSTGIS_HOSTNAME=${POSTGIS_HOSTNAME}
      - POSTGIS_USER=${POSTGIS_USER}
      - SHAPE_DATABASE_NAME=${SHAPE_DATABASE_NAME}
    volumes:
      - ${IMPORT_PATH}shp:/shp:ro
      - ./import/osmborder.sh:/osmborder.sh:ro
    command: bash /osmborder.sh

  shapes:
    image: "img-postgis:0.9.1"
    depends_on:
      - postgis
    networks: 
      - gis
    environment:
      - POSTGIS_HOSTNAME=${POSTGIS_HOSTNAME}
      - POSTGIS_USER=${POSTGIS_USER}
      - SHAPE_DATABASE_NAME=${SHAPE_DATABASE_NAME}
    volumes:
      - ${IMPORT_PATH}shp:/shp:ro
      - ./import/shapes_import.sh:/shapes_import.sh:ro
    command: bash /shapes_import.sh
    
  shapes_postprocessing:
    image: "img-postgis:0.9.1"
    depends_on:
      - postgis
    networks: 
      - gis
    environment:
      - POSTGIS_HOSTNAME=${POSTGIS_HOSTNAME}
      - POSTGIS_USER=${POSTGIS_USER}
      - SHAPE_DATABASE_NAME=${SHAPE_DATABASE_NAME}
    volumes:
      - ./import/shapes_postprocessing.sh:/shapes_postprocessing.sh:ro
    command: bash /shapes_postprocessing.sh
        
  import:
    image: "jawg/imposm3"
    depends_on:
      - postgis
    networks: 
      - gis
    volumes:
      - ${IMPORT_PATH}${IMPORT_FILE}:/opt/imposm3/osmdata.osm.pbf:ro
      - ${IMPOSM_MAPPING}:/opt/imposm3/mapping.yaml:ro
    command: import -mapping mapping.yaml -read osmdata.osm.pbf -overwritecache -write -optimize -connection 'postgis://${POSTGIS_USER}@${POSTGIS_HOSTNAME}/'${DATABASE_NAME}'?prefix=NONE'

  postprocessing:
    image: "img-postgis:0.9.1"
    depends_on:
      - postgis
    networks: 
      - gis
    environment:
      - POSTGIS_HOSTNAME=${POSTGIS_HOSTNAME}
      - POSTGIS_USER=${POSTGIS_USER}
      - DATABASE_NAME=${DATABASE_NAME}
    volumes:
      - ./import/postprocessing.sh:/import/postprocessing.sh:ro
    command: bash /import/postprocessing.sh

  checkdb:
    image: "img-postgis:0.9.1"
    depends_on:
      - postgis
    networks: 
      - gis
    command: psql -h ${POSTGIS_HOSTNAME} -U ${POSTGIS_USER} -d ${DATABASE_NAME} -c "SELECT COUNT(*) from pg_stat_activity;" 

  seed_global:
    image: "tegola:master"
    user: 1000:1000
    depends_on:
      - postgis
    networks: 
      - gis
    volumes:
      - ./serve/config/cyclemap.toml:/data/config.toml:ro
      - ./serve/.cache:/cache
    ports:
      - "${TEGOLA_PORT}:8080"
    command: cache seed tile-name 0/0/0 --config /data/config.toml --min-zoom 3 --max-zoom 6 --map global --overwrite

  seed_local:
    image: tegola:master
    user: 1000:1000
    depends_on:
      - postgis
    networks: 
      - gis
    volumes:
      - ./serve/config/cyclemap.toml:/data/config.toml:ro
      - ./serve/tiles_munich.txt:/data/tiles_munich.txt:ro
      - ./serve/.cache:/cache
    ports:
      - "${TEGOLA_PORT}:8080"
    # command: cache seed tile-list /data/tiles_munich.txt --config /data/config.toml --min-zoom 8 --max-zoom 14 --map local --overwrite
    command: cache seed --bounds "9.140625,46.80005968,13.35937466,48.92249926" --config /data/config.toml --min-zoom 7 --max-zoom 14 --map local --overwrite
    

networks:
  gis:
    name: gis

volumes:
  pgdata:
    external:
      name: vectortiles_db
