[webserver]
port = ":8080"

[cache]
type="file"             # cache type
basepath="/cache"       # cache specific config

# register data providers
[[providers]]
name = "osm"           # provider name is referenced from map layers
type = "postgis"        # the type of data provider. currently only supports postgis
host = "postgis"      # postgis database host
port = 5432             # postgis database port
database = "vector"       # postgis database name
user = "postgres"         # postgis database user
password = ""           # postgis database password
srid = 3857             # The default srid for this provider. If not provided it will be WebMercator (3857)

    [[providers.layers]]
    name = "admin"
    tablename = "import.osm_admin"
    geometry_fieldname = "geometry"
    id_fieldname = "id"
    fields = "type, admin_level"

    [[providers.layers]]
    name = "amenities"
    tablename = "import.osm_amenities"
    geometry_fieldname = "geometry"
    id_fieldname = "id"
    fields = "name, type"

    [[providers.layers]]
    name = "buildings"
    tablename = "import.osm_buildings"
    geometry_fieldname = "geometry"
    id_fieldname = "id"

    [[providers.layers]]
    name = "roads"
    # tablename = "import.osm_roads"
    # geometry_fieldname = "geometry"
    # id_fieldname = "id"
    sql = "SELECT id, ST_AsBinary(geometry) as geom, type as class FROM import.osm_roads WHERE geometry && !BBOX!"

[[maps]]
name = "osm"

    [[maps.layers]]
    provider_layer = "osm.admin"
    min_zoom = 1
    max_zoom = 24

    [[maps.layers]]
    provider_layer = "osm.amenities"
    min_zoom = 1
    max_zoom = 24

    [[maps.layers]]
    provider_layer = "osm.buildings"
    min_zoom = 13
    max_zoom = 24    

    [[maps.layers]]
    provider_layer = "osm.roads"
    min_zoom = 12
    max_zoom = 24 
    dont_simplify = true